const confusingBrowserGlobals = require("confusing-browser-globals");

module.exports = {
  "accessor-pairs": "off",
  "array-bracket-newline": "off",
  "array-bracket-spacing": "off",
  "array-callback-return": ["error", { allowImplicit: false }],
  "array-element-newline": "off",
  "arrow-body-style": "off",
  "arrow-parens": "off",
  "arrow-spacing": "off",
  "block-scoped-var": "error",
  "block-spacing": "off",
  "brace-style": "off",
  "callback-return": "off",
  camelcase: "off",
  "capitalized-comments": "off",
  "class-methods-use-this": "error",
  "comma-dangle": "off",
  "comma-spacing": "off",
  "comma-style": "off",
  complexity: "off",
  "computed-property-spacing": "off",
  "consistent-return": "error",
  "consistent-this": "off",
  "constructor-super": "error",
  curly: "off",
  "default-case": "error",
  "default-param-last": "error",
  "dot-location": "off",
  "dot-notation": "off",
  "eol-last": "off",
  eqeqeq: ["error", "always", { null: "ignore" }],
  "for-direction": "error",
  "func-call-spacing": "off",
  "func-name-matching": "off",
  "func-names": ["error", "as-needed"],
  "func-style": "off",
  "function-call-argument-newline": "off",
  "function-paren-newline": "off",
  "generator-star-spacing": "off",
  "getter-return": "error",
  "global-require": "off",
  "grouped-accessor-pairs": "error",
  "guard-for-in": "error",
  "handle-callback-err": "off",
  "id-blacklist": "off",
  "id-length": "off",
  "id-match": "off",
  "implicit-arrow-linebreak": "off",
  indent: "off",
  "init-declarations": "off",
  "jsx-quotes": "off",
  "key-spacing": "off",
  "keyword-spacing": "off",
  "line-comment-position": "off",
  "linebreak-style": "off",
  "lines-around-comment": "off",
  "lines-between-class-members": "off",
  "max-classes-per-file": "off",
  "max-depth": "off",
  "max-len": "off",
  "max-lines": "off",
  "max-lines-per-function": "off",
  "max-nested-callbacks": "off",
  "max-params": "off",
  "max-statements": "off",
  "max-statements-per-line": "off",
  "multiline-comment-style": "off",
  "multiline-ternary": "off",
  "new-cap": ["error", { newIsCap: true, capIsNew: false }],
  "new-parens": "error",
  "newline-per-chained-call": "off",
  "no-alert": "warn",
  "no-array-constructor": "error",
  "no-async-promise-executor": "error",
  "no-await-in-loop": "off",
  "no-bitwise": "off",
  "no-buffer-constructor": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-confusing-arrow": "off",
  "no-console": "warn",
  "no-const-assign": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-constructor-return": "error",
  "no-continue": "off",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-div-regex": "off",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": "error",
  "no-else-return": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-function": "error",
  "no-empty-pattern": "error",
  "no-eq-null": "off",
  "no-eval": "error",
  "no-ex-assign": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-extra-parens": "off",
  "no-extra-semi": "off",
  "no-fallthrough": "error",
  "no-floating-decimal": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-implicit-globals": "off",
  "no-implied-eval": "error",
  "no-import-assign": "error",
  "no-inline-comments": "off",
  "no-inner-declarations": ["error", "both"],
  "no-invalid-regexp": "error",
  "no-invalid-this": "off",
  "no-irregular-whitespace": "error",
  "no-iterator": "error",
  "no-label-var": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-magic-numbers": "off",
  "no-misleading-character-class": "error",
  "no-mixed-operators": "off",
  "no-mixed-requires": "off",
  "no-mixed-spaces-and-tabs": "off",
  "no-multi-assign": "error",
  "no-multi-spaces": "off",
  "no-multi-str": "off",
  "no-multiple-empty-lines": "off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-new": "off",
  "no-new-func": "error",
  "no-new-object": "error",
  "no-new-require": "error",
  "no-new-symbol": "error",
  "no-new-wrappers": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-param-reassign": "off",
  "no-path-concat": "error",
  "no-plusplus": "off",
  "no-process-env": "off",
  "no-process-exit": "warn",
  "no-proto": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-restricted-globals": [
    "error",
    "isFinite",
    "isNaN",
    ...confusingBrowserGlobals,
  ],
  "no-restricted-imports": "off",
  "no-restricted-modules": "off",
  "no-restricted-properties": "off",
  "no-restricted-syntax": "off",
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-setter-return": "error",
  "no-shadow": "warn",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-sync": "off",
  "no-tabs": "off",
  "no-template-curly-in-string": "off",
  "no-ternary": "off",
  "no-this-before-super": "error",
  "no-throw-literal": "error",
  "no-trailing-spaces": "off",
  "no-undef": "error",
  "no-undef-init": "off",
  "no-undefined": "off",
  "no-underscore-dangle": "off",
  "no-unexpected-multiline": "error",
  "no-unmodified-loop-condition": "error",
  "no-unneeded-ternary": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unused-expressions": [
    "error",
    {
      allowShortCircuit: false,
      allowTernary: false,
      allowTaggedTemplates: true,
    },
  ],
  "no-unused-labels": "error",
  "no-unused-vars": "error",
  "no-use-before-define": "off",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-escape": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "no-void": "error",
  "no-warning-comments": "warn",
  "no-whitespace-before-property": "off",
  "no-with": "error",
  "nonblock-statement-body-position": "off",
  "object-curly-newline": "off",
  "object-curly-spacing": "off",
  "object-property-newline": "off",
  "object-shorthand": [
    "error",
    "always",
    {
      avoidQuotes: true,
      ignoreConstructors: false,
      avoidExplicitReturnArrows: false,
    },
  ],
  "one-var": ["error", "never"],
  "one-var-declaration-per-line": "off",
  "operator-assignment": "off",
  "operator-linebreak": "off",
  "padded-blocks": "off",
  "padding-line-between-statements": "off",
  "prefer-arrow-callback": "off",
  "prefer-const": "error",
  "prefer-destructuring": [
    "error",
    {
      VariableDeclarator: {
        array: false,
        object: true,
      },
      AssignmentExpression: {
        array: false,
        object: false,
      },
    },
    {
      enforceForRenamedProperties: false,
    },
  ],
  "prefer-exponentiation-operator": "error",
  "prefer-named-capture-group": "off",
  "prefer-numeric-literals": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "warn",
  "quote-props": "off",
  quotes: "off",
  radix: "error",
  "require-atomic-updates": "off",
  "require-await": "off",
  "require-unicode-regexp": "error",
  "require-yield": "error",
  "rest-spread-spacing": "off",
  semi: "off",
  "semi-spacing": "off",
  "semi-style": "off",
  "sort-imports": "off",
  "sort-keys": "off",
  "sort-vars": "off",
  "space-before-blocks": "off",
  "space-before-function-paren": "off",
  "space-in-parens": "off",
  "space-infix-ops": "off",
  "space-unary-ops": "off",
  "spaced-comment": "off",
  strict: "off",
  "switch-colon-spacing": "off",
  "symbol-description": "error",
  "template-curly-spacing": "off",
  "template-tag-spacing": "off",
  "unicode-bom": "off",
  "use-isnan": [
    "error",
    { enforceForIndexOf: true, enforceForSwitchCase: true },
  ],
  "valid-typeof": ["error", { requireStringLiterals: true }],
  "vars-on-top": "off",
  "wrap-iife": "off",
  "wrap-regex": "off",
  "yield-star-spacing": "off",
  yoda: "off",
};
