version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 99
    assignees:
      - gcangussu
    versioning-strategy: increase
