module.exports = {
  plugins: ["jest"],
  env: { "jest/globals": true },
  rules: {
    "jest/expect-expect": "warn",
    "jest/no-alias-methods": "error",
    "jest/no-commented-out-tests": "warn",
    "jest/no-conditional-expect": "warn",
    "jest/no-deprecated-functions": "error",
    "jest/no-disabled-tests": "warn",
    "jest/no-duplicate-hooks": "warn",
    "jest/no-export": "error",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/no-jasmine-globals": "warn",
    "jest/no-jest-import": "error",
    "jest/no-mocks-import": "error",
    "jest/no-restricted-matchers": [
      "error",
      { resolves: "Use `expect(await promise)` instead." },
    ],
    "jest/no-standalone-expect": "error",
    "jest/no-test-callback": "error",
    "jest/no-test-prefixes": "error",
    "jest/no-test-return-statement": "error",
    "jest/prefer-spy-on": "warn",
    "jest/prefer-to-contain": "error",
    "jest/prefer-to-have-length": "error",
    "jest/valid-describe": "error",
    "jest/valid-expect": "error",
    "jest/valid-expect-in-promise": "error",
  },
};
