const confusingBrowserGlobals = require("confusing-browser-globals");

module.exports = {
  "array-callback-return": ["error", { allowImplicit: false }],
  "block-scoped-var": "error",
  "class-methods-use-this": "error",
  "consistent-return": "warn",
  "constructor-super": "error",
  "default-case": "warn",
  "default-param-last": "warn",
  eqeqeq: ["error", "always", { null: "ignore" }],
  "for-direction": "error",
  "func-name-matching": ["warn", { considerPropertyDescriptor: true }],
  "func-names": ["error", "as-needed"],
  "getter-return": "error",
  "grouped-accessor-pairs": "error",
  "guard-for-in": "error",
  "new-cap": ["error", { newIsCap: true, capIsNew: false }],
  "new-parens": "error",
  "no-alert": "warn",
  "no-array-constructor": "error",
  "no-async-promise-executor": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-console": "warn",
  "no-const-assign": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-constructor-return": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": "error",
  "no-else-return": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-function": "error",
  "no-empty-pattern": "error",
  "no-eval": "error",
  "no-ex-assign": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-fallthrough": "error",
  "no-floating-decimal": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-implied-eval": "error",
  "no-import-assign": "error",
  "no-inner-declarations": ["error", "both"],
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-iterator": "error",
  "no-label-var": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loss-of-precision": "error",
  "no-loop-func": "error",
  "no-misleading-character-class": "error",
  "no-multi-assign": "error",
  "no-new-func": "error",
  "no-new-object": "error",
  "no-new-symbol": "error",
  "no-new-wrappers": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-proto": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-restricted-globals": [
    "error",
    "isFinite",
    "isNaN",
    ...confusingBrowserGlobals,
  ],
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-setter-return": "error",
  "no-shadow": "warn",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-throw-literal": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unmodified-loop-condition": "error",
  "no-unneeded-ternary": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-expressions": [
    "error",
    {
      allowShortCircuit: false,
      allowTernary: false,
      allowTaggedTemplates: true,
      enforceForJSX: true,
    },
  ],
  "no-unused-labels": "error",
  "no-unused-vars": ["warn", { ignoreRestSiblings: true }],
  "no-useless-backreference": "error",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-escape": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "no-void": "error",
  "no-warning-comments": "warn",
  "no-with": "error",
  "object-shorthand": [
    "error",
    "always",
    {
      avoidQuotes: true,
      ignoreConstructors: false,
      avoidExplicitReturnArrows: false,
    },
  ],
  "one-var": ["error", "never"],
  "prefer-const": "error",
  "prefer-destructuring": [
    "error",
    {
      VariableDeclarator: {
        array: false,
        object: true,
      },
      AssignmentExpression: {
        array: false,
        object: false,
      },
    },
    {
      enforceForRenamedProperties: false,
    },
  ],
  "prefer-exponentiation-operator": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "warn",
  radix: "error",
  "require-unicode-regexp": "error",
  "require-yield": "error",
  "symbol-description": "error",
  "use-isnan": [
    "error",
    { enforceForIndexOf: true, enforceForSwitchCase: true },
  ],
  "valid-typeof": ["error", { requireStringLiterals: true }],
};
