module.exports = {
  "unicorn/custom-error-definition": "error",
  "unicorn/error-message": "error",
  "unicorn/explicit-length-check": "warn",
  "unicorn/new-for-builtins": "warn",
  "unicorn/no-abusive-eslint-disable": "error",
  "unicorn/no-array-instanceof": "error",
  "unicorn/no-console-spaces": "warn",
  "unicorn/no-lonely-if": "warn",
  "unicorn/number-literal-case": "warn",
  "unicorn/prefer-array-find": "warn",
  "unicorn/prefer-date-now": "warn",
  "unicorn/prefer-event-key": "error",
  "unicorn/prefer-flat-map": "warn",
  "unicorn/prefer-includes": "warn",
  "unicorn/prefer-modern-dom-apis": "warn",
  "unicorn/prefer-negative-index": "warn",
  "unicorn/prefer-node-append": "warn",
  "unicorn/prefer-node-remove": "warn",
  "unicorn/prefer-reflect-apply": "warn",
  "unicorn/prefer-set-has": "warn",
  "unicorn/prefer-starts-ends-with": "warn",
  "unicorn/prefer-string-slice": "warn",
  "unicorn/prefer-ternary": "warn",
  "unicorn/prefer-text-content": "warn",
  "unicorn/prefer-trim-start-end": "error",
  "unicorn/throw-new-error": "error",
};
